# ------------------------------------------------------------------------------
# Site settings
# ------------------------------------------------------------------------------

name: Your Name
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace theme for academics. Based on *folio theme.

url:  # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/

# Social
github_username: # put your github username
twitter_username: # put your twitter username
linkedin_username: # put your linkedin username
scholar_authorid: # put your google scholar author id
contact_note: >
  You can even add a little note about which of these is the best way to reach you.

# Blog
blog_name: al-folio
blog_description: simple whitespace theme for academics

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

# ------------------------------------------------------------------------------
# Jekyll settings
# ------------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Math support
kramdown:
  math_engine: mathjax

# Pagination
paginate: 15
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Includes
include: ['_pages']

# Emoji support
emoji_dir: /assets/img/emoji


# Jekyll-Scholar
scholar:

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# ------------------------------------------------------------------------------
# Other advanced settings (don't touch if you are not sure)
# ------------------------------------------------------------------------------
jquery_version: "1.11.1"
katex_version: "0.1.1"
