# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    #build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - /Users/lq/Documents/lqxyz.github.io:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
